@MarionApi_HostAddress = http://localhost:5435

GET {{MarionApi_HostAddress}}/api/system/info
Accept: application/json

###

GET {{MarionApi_HostAddress}}/api/system/dependencies
Accept: application/json

###

GET {{MarionApi_HostAddress}}/health
Accept: application/json

###

GET {{MarionApi_HostAddress}}/alive
Accept: application/json

###