// <auto-generated />
using System;
using Marion.ApiService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marion.ApiService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarionDbContext))]
    partial class MarionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marion.ApiService.Infrastructure.Persistence.AuthSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("SessionId");

                    b.ToTable("MarionAuthSessions", (string)null);
                });

            modelBuilder.Entity("Marion.ApiService.Infrastructure.Persistence.AuthTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("TransactionId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("MarionAuthTransactions", (string)null);
                });

            modelBuilder.Entity("Marion.ApiService.Infrastructure.Persistence.ExternalIdentity", b =>
                {
                    b.Property<string>("Issuer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Issuer", "Subject");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Issuer", "Subject"), false);

                    b.HasIndex("UserId")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("UserId"));

                    b.ToTable("MarionExternalIdentities", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
